
export default {
    SET_USER: "SET_USER",
    SET_VACATIONS: 'SET_VACATIONS',
    DELETE_VACATION: "DELETE_VACATION",
    DELETE_USER:'DELETE_USER',
    EDIT_VACATION:'EDIT_VACATION',
    ADD_FOLLOWE:'ADD_FOLLOWE',
    SAVE_VACATION:'SAVE_VACATION',
    SAVE_ADMIN:'SAVE_ADMIN'
}